'use client';
import {useEffect,useRef,useState} from 'react';
import {authClient,accountRequest} from '@/lib/account/client';
import type {useAccount} from '@/lib/account/use-account';
export function AccountPanel({account}:{account:ReturnType<typeof useAccount>}){
 const [open,setOpen]=useState(false),[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);const connected=account.session&&!account.session.user.is_anonymous;
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'Try again')}finally{setBusy(false)}}
 const client=authClient();
 return <><button className="account-trigger" onClick={()=>setOpen(true)}>{connected?'ACCOUNT':'SIGN IN'}</button><dialog ref={dialog} className="account-panel" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><header><h2>{connected?'ACCOUNT':'SAVE YOUR PROGRESS'}</h2><button aria-label="Close account" onClick={()=>setOpen(false)}>×</button></header>
 {!account.configured?<p>Account sign-in is not enabled yet.</p>:connected?<><p>{account.session?.user.email}</p><button disabled={busy} onClick={()=>void run(async()=>{await account.refresh();setMessage('Synced')})}>SYNC SAVE</button><button disabled={busy} onClick={()=>void run(async()=>{const {data}=await client!.auth.getSession();const save=await accountRequest<{data:unknown}>(data.session!.access_token);const url=URL.createObjectURL(new Blob([JSON.stringify(save.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='krage-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}>EXPORT SAVE</button><button disabled={busy} onClick={()=>void run(async()=>{const {error}=await client!.auth.signOut();if(error)throw error;setOpen(false)})}>SIGN OUT</button></>:<><button disabled={busy||account.loading} onClick={()=>void run(async()=>{await account.preserveGuest();const {error}=await client!.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/'}});if(error)throw error})}>CONTINUE WITH GOOGLE</button><form onSubmit={e=>{e.preventDefault();void run(async()=>{await account.preserveGuest();if(sent){const {error}=await client!.auth.verifyOtp({email,token:code.trim(),type:'email'});if(error)throw error;setOpen(false);setSent(false);setCode('')}else{const {error}=await client!.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(error)throw error;setSent(true);setMessage('Check your email for your code.')}})}}><label>EMAIL<input type="email" autoComplete="email" required value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>VERIFICATION CODE<input autoComplete="one-time-code" inputMode="numeric" required minLength={6} maxLength={10} value={code} onChange={e=>setCode(e.target.value)}/></label>}<button disabled={busy||account.loading}>{sent?'VERIFY & CONNECT':'SEND CODE'}</button>{sent&&<button type="button" disabled={busy} onClick={()=>{setSent(false);setCode('')}}>CHANGE EMAIL / RESEND</button>}</form><small>Guest progress carries into a new account. Existing accounts keep their own save.</small></>}
 {(message||account.error)&&<p role="status">{message||account.error}</p>}{busy&&<p role="status">WORKING…</p>}</dialog></>;
}
