'use client';
import {useEffect,useRef,useState,useMemo,type CSSProperties,type PointerEvent} from 'react';
import {Crosshair,ArrowUp,ArrowDown,ChevronsRight,RotateCcw,Repeat2,SlidersHorizontal} from 'lucide-react';
import type {Arena} from '@/lib/game/engine';
import {emptyInput} from '@/lib/game/core';
import {TOUCH_DEFAULTS,touchPreferences,touchStick,CONTROL_IDS,defaultLayout,cleanLayout,fitTouchLayout,viewportLayout,type ControlId} from '@/lib/game/touch';
let sessionGyro=false;
export function TouchControls({getArena,editor=false,onEdit,onClose}:{getArena:()=>Arena;editor?:boolean;onEdit?:()=>void;onClose?:()=>void}){
 const [prefs,setPrefs]=useState(()=>{try{return touchPreferences(JSON.parse(localStorage.getItem('krage-touch-v1')||'{}'))}catch{return TOUCH_DEFAULTS}});
 const [layout,setLayout]=useState(()=>{try{const saved=localStorage.getItem('krage-touch-layout-v3');return saved?cleanLayout(JSON.parse(saved)):viewportLayout(innerWidth,innerHeight)}catch{return defaultLayout()}});
 const host=useRef<HTMLDivElement>(null);
 const [viewport,setViewport]=useState({width:typeof innerWidth==='number'?innerWidth:844,height:typeof innerHeight==='number'?innerHeight:390,left:0,right:0,top:0,bottom:0});
 useEffect(()=>{const el=host.current;if(!el)return;const resize=()=>{const r=el.getBoundingClientRect(),style=getComputedStyle(el);setViewport({width:r.width,height:r.height,left:parseFloat(style.paddingLeft)||0,right:parseFloat(style.paddingRight)||0,top:parseFloat(style.paddingTop)||0,bottom:parseFloat(style.paddingBottom)||0});};const observer=new ResizeObserver(resize);observer.observe(el);resize();return()=>observer.disconnect();},[]);
 const fitted=useMemo(()=>fitTouchLayout(layout,Math.max(1,viewport.width),Math.max(1,viewport.height),viewport),[layout,viewport]);
 const [advanced,setAdvanced]=useState(false),[selected,setSelected]=useState<ControlId>('fire'),[gyro,setGyro]=useState(sessionGyro),[error,setError]=useState(''),[stick,setStick]=useState({x:0,y:0});
 const pointers=useRef(new Map<number,{kind:ControlId|'look';x:number;y:number}>());
 useEffect(()=>{const engine=getArena();const clear=()=>{pointers.current.clear();document.querySelectorAll('.custom-control[data-held]').forEach(el=>el.removeAttribute('data-held'));if(engine)engine.touch=emptyInput();setStick({x:0,y:0});};clear();
 window.addEventListener('resize',clear);window.addEventListener('blur',clear);window.addEventListener('orientationchange',clear);document.addEventListener('visibilitychange',clear);
 return()=>{clear();window.removeEventListener('resize',clear);window.removeEventListener('blur',clear);window.removeEventListener('orientationchange',clear);document.removeEventListener('visibilitychange',clear)};},[getArena]);
 useEffect(()=>{if(!gyro||editor)return;const motion=(e:DeviceMotionEvent)=>{const r=e.rotationRate;if(!r)return;const dt=Math.min(.04,(e.interval||16)/1000),angle=(screen.orientation?.angle??90)*Math.PI/180;
 getArena().look(((r.beta??0)*Math.sin(angle)+(r.alpha??0)*Math.cos(angle))*dt*4*prefs.sensitivity,(r.gamma??0)*dt*4*prefs.sensitivity);};window.addEventListener('devicemotion',motion);return()=>window.removeEventListener('devicemotion',motion);},[gyro,editor,getArena,prefs.sensitivity]);
 async function toggleGyro(){if(gyro){setGyro(false);return;}try{if(!window.isSecureContext||!window.DeviceMotionEvent)throw Error('Gyro needs HTTPS and motion support.');const api=window.DeviceMotionEvent as typeof DeviceMotionEvent & {requestPermission?:()=>Promise<string>};if(api.requestPermission&&await api.requestPermission()!=='granted')throw Error('Motion permission denied.');setGyro(true);setError('');}catch(e){setError(e instanceof Error?e.message:'Gyro unavailable.')}}
 function down(e:PointerEvent<HTMLElement>,kind:ControlId|'look'){
 e.preventDefault();if([...pointers.current.values()].some(p=>p.kind===kind))return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{kind,x:e.clientX,y:e.clientY});
 if(editor){if(kind!=='look')setSelected(kind);return;}
 e.currentTarget.dataset.held='true';
 const engine=getArena();if(kind==='reload')engine.input.reload=true;else if(kind==='swap')engine.input.weapon=engine.match.player.weapon===3?engine.match.player.primary:3;else if(kind!=='look'&&kind!=='stick')engine.touch[kind]=true;
 }
 function move(e:PointerEvent<HTMLElement>){const p=pointers.current.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;
 if(editor){if(p.kind!=='look'){const id=p.kind;setLayout(old=>cleanLayout({...old,[id]:{...old[id],x:old[id].x+dx/viewport.width*100,y:old[id].y+dy/viewport.height*100}}));p.x=e.clientX;p.y=e.clientY;}return;}
 if(p.kind==='stick'){const v=touchStick(dx,dy,fitted.stick.size*.45);Object.assign(getArena().touch,v);setStick({x:v.right*30,y:-v.forward*30});}else if(p.kind==='look'||p.kind==='fire'){getArena().look(dx*1.8*prefs.sensitivity,dy*1.8*prefs.sensitivity);p.x=e.clientX;p.y=e.clientY;}}
 function end(e:PointerEvent<HTMLElement>){delete e.currentTarget.dataset.held;const p=pointers.current.get(e.pointerId);if(!p)return;pointers.current.delete(e.pointerId);if(editor)return;if(p.kind==='stick'){getArena().touch.forward=getArena().touch.right=0;setStick({x:0,y:0});}else if(p.kind!=='look'&&p.kind!=='reload'&&p.kind!=='swap')getArena().touch[p.kind]=false;}
 useEffect(()=>{if(!editor)return;const key=(e:KeyboardEvent)=>{e.stopPropagation();if(e.code==='Escape'){e.preventDefault();onClose?.();}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[editor,onClose]);
 const icons={stick:null,fire:<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M11 25V12l5-7 5 7v13zM11 20h10M11 12h10"/><path d="M5 11v8M27 11v8"/></svg>,ads:<Crosshair/>,jump:<ArrowUp/>,crouch:<ArrowDown/>,slide:<ChevronsRight/>,reload:<RotateCcw/>,swap:<Repeat2/>};
 function save(){try{localStorage.setItem('krage-touch-v1',JSON.stringify(prefs));localStorage.setItem('krage-touch-layout-v3',JSON.stringify(fitted));sessionGyro=gyro;onClose?.();}catch{setError('Storage unavailable. Allow site storage to save controls.')}}
 return <div ref={host} className={'mobile-controls custom-touch '+(editor?'touch-editor':'')} onContextMenu={e=>e.preventDefault()}>
 {!editor&&<div className="mobile-look" onPointerDown={e=>down(e,'look')} onPointerMove={e=>move(e)} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e)} onLostPointerCapture={e=>end(e)}/>}
 {CONTROL_IDS.map(id=><button key={id} aria-label={id==='stick'?'Movement joystick':id==='ads'?'Aim / knife stab':id==='swap'?'Switch weapon':id} aria-pressed={editor?selected===id:undefined} className={`custom-control mobile-${id}`} style={{'--control-size':`${fitted[id].size}px`,left:`clamp(calc(var(--control-size)/2 + env(safe-area-inset-left) + 4px), ${fitted[id].x}%, calc(100% - var(--control-size)/2 - env(safe-area-inset-right) - 4px))`,top:`clamp(calc(var(--control-size)/2 + env(safe-area-inset-top) + 4px), ${fitted[id].y}%, calc(100% - var(--control-size)/2 - env(safe-area-inset-bottom) - 4px))`,opacity:editor?Math.max(.55,layout[id].opacity):layout[id].opacity} as CSSProperties} onPointerDown={e=>down(e,id)} onPointerMove={e=>move(e)} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e)} onLostPointerCapture={e=>end(e)}>{id==='stick'?<i style={{transform:`translate(${stick.x}px,${stick.y}px)`}}/>:<>{icons[id]}<small>{id==='ads'?'AIM':id.toUpperCase()}</small></>}</button>)}
 {!editor&&<button className="mobile-adjust" aria-label="Touch settings" onClick={onEdit}><SlidersHorizontal/></button>}
 {editor&&<section className={'touch-editor-panel compact-editor '+(advanced?'expanded':'')} aria-label="Mobile controls editor"><header><strong>{selected.toUpperCase()}</strong><button aria-label="Close editor" onClick={onClose}>×</button></header><label className="editor-size">SIZE<button aria-label="Smaller control" onClick={()=>setLayout(cleanLayout({...layout,[selected]:{...layout[selected],size:layout[selected].size-4}}))}>−</button><output>{layout[selected].size}</output><button aria-label="Larger control" onClick={()=>setLayout(cleanLayout({...layout,[selected]:{...layout[selected],size:layout[selected].size+4}}))}>+</button></label><div className="editor-actions"><button aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>OPTIONS</button><button onClick={save}>SAVE</button></div>{advanced&&<div className="editor-options"><label>OPACITY<input type="range" min=".2" max="1" step=".05" value={layout[selected].opacity} onChange={e=>setLayout({...layout,[selected]:{...layout[selected],opacity:Number(e.target.value)}})}/></label><label>SENSITIVITY<input type="range" min=".4" max="2.4" step=".1" value={prefs.sensitivity} onChange={e=>setPrefs({...prefs,sensitivity:Number(e.target.value)})}/></label><button onClick={()=>void toggleGyro()}>GYRO {gyro?'ON':'OFF'}</button><button onClick={()=>setLayout(viewportLayout(viewport.width,viewport.height,true))}>LEFT HAND</button><button onClick={()=>{setLayout(viewportLayout(viewport.width,viewport.height));setPrefs(TOUCH_DEFAULTS);setGyro(false)}}>RESET</button></div>}<small>Tap to select · Drag to move</small>{error&&<output>{error}</output>}</section>}
 </div>;
}
