'use client';
import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
import {Crosshair,ArrowUp,ArrowDown,ChevronsRight,RotateCcw,Repeat2,SlidersHorizontal} from 'lucide-react';
import type {Arena} from '@/lib/game/engine';
import {emptyInput} from '@/lib/game/core';
import {TOUCH_DEFAULTS,touchPreferences,touchStick,CONTROL_IDS,defaultLayout,cleanLayout,type ControlId} from '@/lib/game/touch';
let sessionGyro=false;
export function TouchControls({getArena,editor=false,onEdit,onClose}:{getArena:()=>Arena;editor?:boolean;onEdit?:()=>void;onClose?:()=>void}){
 const [prefs,setPrefs]=useState(()=>{try{return touchPreferences(JSON.parse(localStorage.getItem('krage-touch-v1')||'{}'))}catch{return TOUCH_DEFAULTS}});
 const [layout,setLayout]=useState(()=>{try{return cleanLayout(JSON.parse(localStorage.getItem('krage-touch-layout-v2')||'{}'))}catch{return defaultLayout()}});
 const [selected,setSelected]=useState<ControlId>('fire'),[gyro,setGyro]=useState(sessionGyro),[error,setError]=useState(''),[stick,setStick]=useState({x:0,y:0});
 const pointers=useRef(new Map<number,{kind:ControlId|'look';x:number;y:number}>());
 useEffect(()=>{const engine=getArena();const clear=()=>{pointers.current.clear();if(engine)engine.touch=emptyInput();setStick({x:0,y:0});};clear();
 window.addEventListener('blur',clear);window.addEventListener('orientationchange',clear);document.addEventListener('visibilitychange',clear);
 return()=>{clear();window.removeEventListener('blur',clear);window.removeEventListener('orientationchange',clear);document.removeEventListener('visibilitychange',clear)};},[getArena]);
 useEffect(()=>{if(!gyro||editor)return;const motion=(e:DeviceMotionEvent)=>{const r=e.rotationRate;if(!r)return;const dt=Math.min(.04,(e.interval||16)/1000),angle=(screen.orientation?.angle??90)*Math.PI/180;
 getArena().look(((r.beta??0)*Math.sin(angle)+(r.alpha??0)*Math.cos(angle))*dt*4*prefs.sensitivity,(r.gamma??0)*dt*4*prefs.sensitivity);};window.addEventListener('devicemotion',motion);return()=>window.removeEventListener('devicemotion',motion);},[gyro,editor,getArena,prefs.sensitivity]);
 async function toggleGyro(){if(gyro){setGyro(false);return;}try{if(!window.isSecureContext||!window.DeviceMotionEvent)throw Error('Gyro needs HTTPS and motion support.');const api=window.DeviceMotionEvent as typeof DeviceMotionEvent & {requestPermission?:()=>Promise<string>};if(api.requestPermission&&await api.requestPermission()!=='granted')throw Error('Motion permission denied.');setGyro(true);setError('');}catch(e){setError(e instanceof Error?e.message:'Gyro unavailable.')}}
 function down(e:PointerEvent<HTMLElement>,kind:ControlId|'look'){
 e.preventDefault();if([...pointers.current.values()].some(p=>p.kind===kind))return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{kind,x:e.clientX,y:e.clientY});
 if(editor){if(kind!=='look')setSelected(kind);return;}
 const engine=getArena();if(kind==='reload')engine.input.reload=true;else if(kind==='swap')engine.input.weapon=engine.match.player.weapon===3?engine.match.player.primary:3;else if(kind!=='look'&&kind!=='stick')engine.touch[kind]=true;
 }
 function move(e:PointerEvent<HTMLElement>){const p=pointers.current.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;
 if(editor){if(p.kind!=='look'){const id=p.kind;setLayout(old=>cleanLayout({...old,[id]:{...old[id],x:old[id].x+dx/innerWidth*100,y:old[id].y+dy/innerHeight*100}}));p.x=e.clientX;p.y=e.clientY;}return;}
 if(p.kind==='stick'){const v=touchStick(dx,dy,layout.stick.size*.45);Object.assign(getArena().touch,v);setStick({x:v.right*30,y:-v.forward*30});}else if(p.kind==='look'||p.kind==='fire'){getArena().look(dx*1.8*prefs.sensitivity,dy*1.8*prefs.sensitivity);p.x=e.clientX;p.y=e.clientY;}}
 function end(e:PointerEvent<HTMLElement>){const p=pointers.current.get(e.pointerId);if(!p)return;pointers.current.delete(e.pointerId);if(editor)return;if(p.kind==='stick'){getArena().touch.forward=getArena().touch.right=0;setStick({x:0,y:0});}else if(p.kind!=='look'&&p.kind!=='reload'&&p.kind!=='swap')getArena().touch[p.kind]=false;}
 useEffect(()=>{if(!editor)return;const key=(e:KeyboardEvent)=>{e.stopPropagation();if(e.code==='Escape'){e.preventDefault();onClose?.();}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[editor,onClose]);
 const icons={stick:null,fire:<Crosshair/>,ads:<Crosshair/>,jump:<ArrowUp/>,crouch:<ArrowDown/>,slide:<ChevronsRight/>,reload:<RotateCcw/>,swap:<Repeat2/>};
 function save(){try{localStorage.setItem('krage-touch-v1',JSON.stringify(prefs));localStorage.setItem('krage-touch-layout-v2',JSON.stringify(layout));sessionGyro=gyro;onClose?.();}catch{setError('Storage unavailable. Allow site storage to save controls.')}}
 return <div className={'mobile-controls custom-touch '+(editor?'touch-editor':'')} onContextMenu={e=>e.preventDefault()}>
 {!editor&&<div className="mobile-look" onPointerDown={e=>down(e,'look')} onPointerMove={e=>move(e)} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e)} onLostPointerCapture={e=>end(e)}/>}
 {CONTROL_IDS.map(id=><button key={id} aria-label={id==='stick'?'Movement joystick':id==='ads'?'Aim / knife stab':id==='swap'?'Switch weapon':id} aria-pressed={editor?selected===id:undefined} className={`custom-control mobile-${id}`} style={{'--control-size':`${layout[id].size}px`,left:`clamp(calc(var(--control-size)/2 + env(safe-area-inset-left) + 4px), ${layout[id].x}%, calc(100% - var(--control-size)/2 - env(safe-area-inset-right) - 4px))`,top:`clamp(calc(var(--control-size)/2 + env(safe-area-inset-top) + 4px), ${layout[id].y}%, calc(100% - var(--control-size)/2 - env(safe-area-inset-bottom) - 4px))`,opacity:editor?Math.max(.55,layout[id].opacity):layout[id].opacity} as CSSProperties} onPointerDown={e=>down(e,id)} onPointerMove={e=>move(e)} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e)} onLostPointerCapture={e=>end(e)}>{id==='stick'?<i style={{transform:`translate(${stick.x}px,${stick.y}px)`}}/>:<>{icons[id]}<small>{id==='ads'?'AIM':id.toUpperCase()}</small></>}</button>)}
 {!editor&&<button className="mobile-adjust" aria-label="Touch settings" onClick={onEdit}><SlidersHorizontal/></button>}
 {editor&&<section className="touch-editor-panel" aria-label="Mobile controls editor"><header><strong>MOBILE CONTROLS</strong><button onClick={save}>SAVE</button><button onClick={onClose}>CANCEL</button></header><div className="touch-editor-fields"><label>BUTTON<select value={selected} onChange={e=>setSelected(e.target.value as ControlId)}>{CONTROL_IDS.map(id=><option key={id}>{id}</option>)}</select></label>{(['size','opacity','x','y'] as const).map(key=><label key={key}>{key==='x'?'HORIZONTAL':key==='y'?'VERTICAL':key.toUpperCase()}<input aria-label={`Button ${key}`} type="range" min={key==='size'?44:key==='opacity'?.2:4} max={key==='size'?(selected==='stick'?160:100):key==='opacity'?1:96} step={key==='opacity'?.05:1} value={layout[selected][key]} onChange={e=>setLayout({...layout,[selected]:{...layout[selected],[key]:Number(e.target.value)}})}/></label>)}<label>SENSITIVITY<input type="range" min=".4" max="2.4" step=".1" value={prefs.sensitivity} onChange={e=>setPrefs({...prefs,sensitivity:Number(e.target.value)})}/></label><button onClick={()=>void toggleGyro()}>GYRO {gyro?'ON':'OFF'}</button><button onClick={()=>setLayout(defaultLayout(true))}>LEFT HAND</button><button onClick={()=>{setLayout(defaultLayout());setPrefs(TOUCH_DEFAULTS);setGyro(false)}}>RESET</button></div><small>Drag controls to position them.</small>{error&&<output>{error}</output>}</section>}
 </div>;
}
